spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8090/oauth/token

logging:
  level:
    org.springframework.security.oauth2.jwt: trace
    org.springframework.security.oauth2.server.resource.web: trace
    org.springframework.security.authentication: trace