#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: 345345fsdgsf5345
#    client:
#      client-id: eagleeye
#      id: eagleeye
#      client-secret: thisissecret
#      scope: webclient
#      authorized-grant-types: refresh_token, password, client_credentials
#  user:
#    name: john.carnell
#    password: password1
#    role: USER

#spring:
#  security:
#    user:
#      name: john.carnell
#      password: password1
#      roles: USER
#endpoints:
#  actuator:
#    enabled: true

spring:
  security:
    user:
      name: josh
      password: pw
      roles: user
  thymeleaf:
    cache: false
security:
  oauth2:
    resource:
      jwt:
        key-value: 345345fsdgsf5345
    client:
      client-id: client-1234
      client-secret: secret
      grant-type: password, authorization_code
      scope: profile
      registered-redirect-uri: http://localhost:8080/login/oauth2/code/ryanair
    authorization:
      jwt:
        key-store: classpath:.keystore-oauth2-demo
        key-value: admin1234
#      filter-order: 5

server:
  port: 8090

logging:
  level:
    org.springframework.security: info
    org.springframework.security.oauth2: info

