spring:
  security:
    user:
      name: josh
      password: pw
      roles: user
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: root
security:
  oauth2:
    client:
      client-id: client-1234
      client-secret: secret
      grant-type: password, authorization_code
      scope: profile
      registered-redirect-uri: https://app.getpostman.com/oauth2/callback
      access-token-validity-seconds: 60
    authorization:
      jwt:
        key-store: classpath:.keystore-oauth2-demo
        #        key-value: admin1234
        key-store-password: admin1234
        key-alias: oauth2-demo-key
      check-token-access: permitAll()

server:
  port: 8090

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.security.core.userdetails.jdbc: debug
#    org.springframework.boot.autoconfigure: debug
