spring:
  security:
    user:
      name: josh
      password: pw
      roles: user
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: root
security:
  oauth2:
    client:
      client-id: client-1234
      client-secret: secret
      grant-type: password, authorization_code
      scope: profile
      registered-redirect-uri: https://app.getpostman.com/oauth2/callback
    authorization:
      jwt:
        key-store: classpath:.keystore-oauth2-demo
#        key-value: admin1234
        key-store-password: admin1234
        key-alias: oauth2-demo-key
#      filter-order: 5

server:
  port: 8090

logging:
  level:
    org.springframework.security: info
    org.springframework.security.oauth2: info
#    org.springframework.boot.autoconfigure: debug
